const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED';
const INCREMENT = 'counter/INCREMENT';
const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED';
const DECREMENT = 'counter/DECREMENT';


export {
    INCREMENT_REQUESTED,
    INCREMENT,
    DECREMENT_REQUESTED,
    DECREMENT
};